# Generated by Django 5.2.8 on 2025-11-18 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_kodu', models.CharField(max_length=20, unique=True, verbose_name='Ders Kodu')),
                ('ders_adi', models.CharField(max_length=200, verbose_name='Ders Adı')),
                ('ogretmen', models.CharField(max_length=200, verbose_name='Öğretmen')),
                ('kredi', models.IntegerField(default=3, verbose_name='Kredi')),
                ('haftalik_ders_saati', models.IntegerField(default=3, verbose_name='Haftalık Ders Saati')),
                ('devam_zorunlulugu', models.IntegerField(default=70, verbose_name='Devam Zorunluluğu (%)')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
            },
        ),
        migrations.CreateModel(
            name='Devamsizlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devamsiz_saat', models.IntegerField(default=0, verbose_name='Devamsız Kalınan Saat')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevamsizlikTakvimi.ders', verbose_name='Ders')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Devamsızlık',
                'verbose_name_plural': 'Devamsızlıklar',
                'ordering': ['-tarih'],
                'unique_together': {('ogrenci', 'ders')},
            },
        ),
    ]
