# Generated by Django 4.2.7 on 2025-12-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kullanıcılar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='bolum',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bölüm'),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='isim',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='rol',
            field=models.CharField(choices=[('user', 'Normal Kullanıcı'), ('superadmin', 'Süper Admin'), ('club_moderator', 'Kulüp Yetkilisi'), ('instructor', 'Öğretim Görevlisi')], default='user', max_length=20, verbose_name='Rol'),
        ),
    ]
