# Generated by Django 5.2.8 on 2025-11-18 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('kategori', models.CharField(choices=[('genel', 'Genel'), ('akademik', 'Akademik'), ('sosyal', 'Sosyal'), ('acil', 'Acil')], default='genel', max_length=20, verbose_name='Kategori')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('goruntulenme', models.IntegerField(default=0, verbose_name='Görüntülenme')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('kategori', models.CharField(choices=[('konser', 'Konser'), ('konferans', 'Konferans'), ('spor', 'Spor'), ('sosyal', 'Sosyal'), ('akademik', 'Akademik'), ('tiyatro', 'Tiyatro')], max_length=20, verbose_name='Kategori')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('baslangic_saati', models.TimeField(verbose_name='Başlangıç Saati')),
                ('bitis_saati', models.TimeField(verbose_name='Bitiş Saati')),
                ('konum', models.CharField(max_length=200, verbose_name='Konum')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('katilimcilar', models.ManyToManyField(blank=True, related_name='katildigi_etkinlikler', to=settings.AUTH_USER_MODEL, verbose_name='Katılımcılar')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olusturdugu_etkinlikler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='Kulup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Kulüp Adı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('kategori', models.CharField(choices=[('teknoloji', 'Teknoloji'), ('spor', 'Spor'), ('sanat', 'Sanat'), ('sosyal', 'Sosyal'), ('akademik', 'Akademik')], max_length=20, verbose_name='Kategori')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kurucu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurucusu_oldugu_kulupler', to=settings.AUTH_USER_MODEL, verbose_name='Kurucu')),
                ('uyeler', models.ManyToManyField(blank=True, related_name='kulupleri', to=settings.AUTH_USER_MODEL, verbose_name='Üyeler')),
            ],
            options={
                'verbose_name': 'Kulüp',
                'verbose_name_plural': 'Kulüpler',
                'ordering': ['ad'],
            },
        ),
    ]
